//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dzieci
    {
        public Dzieci()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int IDDziecka { get; set; }
        public Nullable<int> IDKlienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Plec { get; set; }
        public Nullable<int> SredniaOcena { get; set; }
    
        public virtual KlienciLokujacy KlienciLokujacy { get; set; }
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
