//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKid
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlienciPodejmujacy
    {
        public KlienciPodejmujacy()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int IDKlienta { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
