//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKid
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlienciLokujacy
    {
        public KlienciLokujacy()
        {
            this.Dzieci = new HashSet<Dzieci>();
        }
    
        public int IDKlienta { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public Nullable<int> NrDomu { get; set; }
        public Nullable<int> NrKonta { get; set; }
    
        public virtual ICollection<Dzieci> Dzieci { get; set; }
        public virtual Klienci Klienci { get; set; }
    }
}
