//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogledziny
    {
        public int IDOgledzin { get; set; }
        public Nullable<int> IDWypozyczenia { get; set; }
        public Nullable<int> IDNiani { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string NazwiskoLekarza { get; set; }
        public string Status { get; set; }
        public string Rezultat { get; set; }
    
        public virtual Nianie Nianie { get; set; }
        public virtual Wypozyczenia Wypozyczenia { get; set; }
    }
}
