//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAKid
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheRAKDatabaseEntities : DbContext
    {
        public TheRAKDatabaseEntities()
            : base("name=TheRAKDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dzieci> Dzieci { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<KlienciLokujacy> KlienciLokujacy { get; set; }
        public virtual DbSet<KlienciPodejmujacy> KlienciPodejmujacy { get; set; }
        public virtual DbSet<Komunikaty> Komunikaty { get; set; }
        public virtual DbSet<Nianie> Nianie { get; set; }
        public virtual DbSet<Ogledziny> Ogledziny { get; set; }
        public virtual DbSet<Supernianie> Supernianie { get; set; }
        public virtual DbSet<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
